import { NewCorporateInfo } from '@app/postgres-db/schemas/corporate-info.schema';

export const edagTemplate: NewCorporateInfo = {
  titleBar: 'Light',
  dashboardFontColor: '#FFF',
  dashboardPrimaryColor: '#2D3244',
  dashboardSecondaryColor: '#3D4760',
  fontColor: '#FFF',
  headerFontColor: '#FFF',
  headerLogoId: null,
  headerPrimaryColor: '#3d4760',
  headerSecondaryColor: '#3d4760',
  headerTitleAdmin: 'Smart Region Dashboard',
  headerTitleDashboards: 'Dashboards',
  logo: null,
  menuActiveColor: '#FFF',
  menuFontColor: '#fff',
  menuHoverColor: '#99a4c3ff',
  menuLogoId: null,
  menuPrimaryColor: '#3D4760',
  menuSecondaryColor: '#1d2330',
  panelBorderColor: '#3D4760',
  panelBorderRadius: '4px',
  panelBorderSize: '4px',
  panelFontColor: '#FFF',
  panelPrimaryColor: '#3D4760',
  panelSecondaryColor: '#3D4760',
  showHeaderLogo: true,
  showMenuLogo: true,
  widgetBorderColor: '#3D4760',
  widgetBorderRadius: '4px',
  widgetBorderSize: '4px',
  widgetFontColor: '#FFF',
  widgetPrimaryColor: '#3D4760',
  widgetSecondaryColor: '#3D4760',
  scrollbarBackground: '#b9c2ee',
  scrollbarColor: '#3D4760',
  menuActiveFontColor: '#1d2330',
  useColorTransitionHeader: false,
  useColorTransitionMenu: false,
  saveButtonColor: '#f5c442',
  saveHoverButtonColor: '#f7c543',
  cancelButtonColor: '#803535ff',
  cancelHoverButtonColor: '#ffffffff',
  fontFamily: 'Arial',
  barChartAxisLabelSize: '14',
  barChartAxisLineColor: '#ffffffff',
  barChartAxisTicksFontSize: '14',
  barChartCurrentValuesColors: [
    '#FFA500',
    '#FF4500',
    '#00FF00',
    '#6f3939ff',
    '#d61010ff',
    '#a28d8dff',
    '#618369ff',
    '#7e6969ff',
    '#3d2f2fff',
    '#ecddddff',
  ],
  barChartGridColor: '#ffffffff',
  barChartLegendFontSize: '14',
  barChartTicksFontColor: '#ffffffff',
  coloredSliderArrowColor: null,
  coloredSliderBigValueFontColor: null,
  coloredSliderBigValueFontSize: null,
  coloredSliderLabelFontColor: null,
  coloredSliderLabelFontSize: null,
  coloredSliderUnitFontSize: null,
  dashboardHeadlineFontSize: '24px',
  degreeChart180BgColor: '#190f50ff',
  degreeChart180FillColor: '#ffffffff',
  degreeChart180FontColor: '#ffffffff',
  degreeChart180FontSize: '20',
  degreeChart180UnitFontSize: '15',
  degreeChart360BgColor: '#004cafff',
  degreeChart360FillColor: '#ffffffff',
  degreeChart360FontColor: '#ffffffff',
  degreeChart360FontSize: '20',
  degreeChart360UnitFontSize: '15',
  iconWithLinkFontColor: '#ffffffff',
  iconWithLinkFontSize: '20',
  iconWithLinkIconColor: '#ffffffff',
  iconWithLinkIconSize: 'xl',
  informationTextFontColor: '#ffffffff',
  informationTextFontSize: '20',
  lineChartAxisLabelFontColor: '#ffffffff',
  lineChartAxisLabelSize: '14',
  lineChartAxisLineColor: '#ffffffff',
  lineChartAxisTicksFontSize: '14',
  lineChartCurrentValuesColors: [
    '#4f94dbff',
    '#755b5bff',
    '#971b1bff',
    '#31586fff',
    '#4bc771ff',
    '#b9c58bff',
    '#2534afb2',
    '#b21dc2ff',
    '#b1a2a2ff',
    '#ce3388ff',
  ],
  lineChartGridColor: '#ffffffff',
  lineChartLegendFontSize: '14',
  lineChartLegendFontColor: '#ffffffff',
  lineChartTicksFontColor: '#ffffffff',
  measurementChartAxisLabelFontColor: '#4f94dbff',
  measurementChartAxisLineColor: '#755b5bff',
  measurementChartAxisTicksFontColor: '#971b1bff',
  measurementChartBarColor: '#31586fff',
  measurementChartBigValueFontColor: '#4bc771ff',
  measurementChartBigValueFontSize: '60',
  measurementChartCardsBgColor: '#ffffff00',
  measurementChartCardsFontColor: '#ffffffff',
  measurementChartCardsIconColors: [
    '#68aff0ff',
    '#dd4bc0ff',
    '#d88935ff',
    '#e71010ff',
  ],
  measurementChartCurrentValuesColors: ['#00c8ffff'],
  measurementChartGridColor: '#ffffffff',
  measurementChartLabelFontColor: '#ffffff00',
  measurementChartTopButtonBgColor: '#ffffffff',
  measurementChartTopButtonFontColor: '#ffffff00',
  measurementChartTopButtonHoverColor: '#000152ff',
  measurementChartTopButtonInactiveBgColor: '#ffffff00',
  panelHeadlineFontSize: '24px',
  pieChartFontColor: '#ffffffff',
  pieChartFontSize: '20',
  pieChartCurrentValuesColors: [
    '#4f94dbff',
    '#755b5bff',
    '#971b1bff',
    '#31586fff',
    '#4bc771ff',
    '#b9c58bff',
    '#2534afb2',
    '#b21dc2ff',
    '#b1a2a2ff',
    '#ce3388ff',
  ],
  stageableChartFontColor: '#ffffffff',
  stageableChartFontSize: '20',
  stageableChartTicksFontColor: '#ffffffff',
  stageableChartTicksFontSize: '10',
  wertFontColor: '#ffffffff',
  widgetHeadlineFontSize: '20',
  widgetSubheadlineFontSize: '16px',
  wertFontSize: '14px',
  wertUnitFontSize: '20',
  barChartAxisLabelColor: '#ffffffff',
  barChartLegendFontColor: '#FFFFFF',
  barChartFilterColor: '#F1B434',
  barChartFilterTextColor: '#1D2330',
  lineChartFilterColor: '#F1B434',
  lineChartFilterTextColor: '#1D2330',
  barChartAxisLabelFontColor: '#FFFFF',
};
