# Stage 1: Build the React app
FROM node:18-alpine as build

WORKDIR /app

COPY . /app

RUN npm install -g npm@latest
RUN apk update && apk upgrade && \
    apk add --no-cache git

RUN npm install

RUN npm run build

# Install 'serve' globally
RUN npm install -g serve

# Expose port 3000
EXPOSE 3000

# Start the application using 'serve'
CMD ["serve", "-s", "build", "-l", "3000"]