# Stage 1: Build the React app
FROM node:16-alpine as build

WORKDIR /app

COPY ./frontend/package*.json ./

ENV REACT_APP_BASE_URL=https://smartcity.wuppertal.de/api
ENV REACT_APP_STADIA_API_KEY=989bd661-957b-4db0-8470-025423367174

RUN npm install

COPY ./frontend .

RUN npm run build

# Stage 2: Serve the React app with Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
