# Use the official Nginx image as the base image
FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration file
COPY ./nginx.conf /etc/nginx/conf.d/
COPY ./server.crt /etc/nginx/conf.d/cert.crt
COPY ./server.key /etc/nginx/conf.d/cert.key

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]