version: '3'
services:
  frontend:
    container_name: smartcity-dashboard-${PROJECT_NAME}
    image: smartcity-dashboard-dev
    build:
      context: .
      dockerfile: ./frontend/DockerfileDev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/node/app
    environment:
      - PORT=3000
      - WATCHPACK_POLLING=true
    env_file:
      - .env
  frontend-service:
    container_name: frontend-service-${PROJECT_NAME}
    image: smartcity-frontend-service-dev
    build:
      context: .
      dockerfile: ./backend/frontendService/DockerfileDev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/frontendService:/home/node/app
    environment:
      - PORT=8080
    env_file:
      - .env
  ql-service:
    container_name: ql-service-${PROJECT_NAME}
    image: smartcity-frontend-service-dev
    build:
      context: .
      dockerfile: ./backend/qlService/DockerfileDev
    ports:
      - "8081:8080"
    volumes:
      - ./backend/qlService:/home/node/app
    environment:
      - PORT=8080
    env_file:
      - .env
  mongodb:
    container_name: smartcity-mongodb-${PROJECT_NAME}
    image: mongo
    command: mongod --port 27021
    ports:
      - "27021:27021"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
