db = db.getSiblingDB("smartcity-dashboard");

db.createCollection("dashboards");
db.createCollection("querydatas");
db.createCollection("roles");
db.createCollection("tabs");
db.createCollection("users");

// Roles insert
db.roles.insertOne({
  _id: "61682bf1cce96b4598075644",
  name: "admin",
});

// Users insert
db.users.insertOne({
  username: "dev-admin",
  password: "$2a$08$NIrP.cxtKw2sYl3JcqBzwuQopo3T82lzlAar3UIpM7Ei.Luh00Xcy",
  roles: ["61682bf1cce96b4598075644"],
});

// Dashboard insert
db.dashboards.insertOne({
  _id: "61b8e8ef2cdf79e0dea2ab3f",
  index: 0,
  name: "Übersicht",
  url: "uebersicht",
  icon: "dashboard",
  visible: true,
  widgets: [
    {
      name: "Klima",
      panels: [
        {
          name: "Temperatur",
          width: 6,
          height: 300,
          tabs: [
            {
              name: "Tab",
              type: "chart",
              text: "",
              apexType: "line",
              apexOptions: {
                grid: { borderColor: "#2f3a4e" },
                yaxis: {
                  forceNiceScale: true,
                  title: { text: "Temperatur [°C]" },
                },
                dataLabels: { enabled: false },
                fill: { opacity: 1 },
                chart: { toolbar: { show: false }, background: "#152437" },
                theme: { mode: "dark", palette: "palette4" },
                colors: ["#ff9f00", "#f6d702", "#1e2738"],
                legend: { position: "top", markers: { radius: 5 } },
                xaxis: {
                  convertedCatToNumeric: true,
                  type: "category",
                  categories: [
                    "17.01.",
                    "18.01.",
                    "19.01.",
                    "20.01.",
                    "21.01.",
                    "22.01.",
                    "23.01.",
                    "24.01.",
                    "25.01.",
                    "26.01.",
                    "27.01.",
                    "28.01.",
                    "29.01.",
                    "30.01.",
                  ],
                  labels: { rotate: 0 },
                  tickAmount: 13,
                },
              },
              apexSeries: [
                {
                  name: "minimale Temperatur",
                  data: [1, 3, 4, 3, 0, 2, 3, 4, 4, 2, 2, 1, 0, -1],
                },
                {
                  name: "maximale Temperatur",
                  data: [3, 4, 6, 5, 2, 6, 7, 7, 7, 5, 4, 5, 3, 2],
                },
              ],
              apexMaxValue: 100,
              apexMaxAlias: "",
              apexMaxColor: "#04beaf",
              timeframe: 0,
              fiwareService: "temperatur",
              entityId: ["luftfeuchtigkeit"],
              attribute: {
                keys: ["Temperatur", "Temp2"],
                aliases: ["Temperatur", "Temp2"],
              },
              values: [],
              decimals: 0,
              aggrMode: "single",
              queryData: { id: { $oid: "61f92d006eb2edbb8b0a8bda" } },
              _id: { $oid: "61f92b716eb2edbb8b0a88f8" },
            },
          ],
          _id: { $oid: "61f92b716eb2edbb8b0a88f7" },
        },
        {
          name: "Luftfeuchtigkeit",
          width: 6,
          height: 300,
          tabs: [
            {
              name: "Tab",
              type: "chart",
              text: "",
              apexType: "line",
              apexOptions: {
                grid: { borderColor: "#2f3a4e" },
                yaxis: {
                  forceNiceScale: true,
                  title: { text: "Luftfeuchtigkeit [%]" },
                },
                dataLabels: { enabled: false },
                fill: { opacity: 1 },
                chart: { toolbar: { show: false }, background: "#152437" },
                theme: { mode: "dark", palette: "palette4" },
                colors: ["#ff9f00", "#1e2738"],
                legend: { position: "top", markers: { radius: 5 } },
                xaxis: {
                  convertedCatToNumeric: true,
                  type: "category",
                  categories: [
                    "17.01.",
                    "18.01.",
                    "19.01.",
                    "20.01.",
                    "21.01.",
                    "22.01.",
                    "23.01.",
                    "24.01.",
                    "25.01.",
                    "26.01.",
                    "27.01.",
                    "28.01.",
                    "29.01.",
                    "30.01.",
                  ],
                  labels: { rotate: 0 },
                  tickAmount: 13,
                },
              },
              apexSeries: [
                {
                  name: "Luftfeuchtigkeit",
                  data: [
                    71, 73, 75, 83, 80, 83, 74, 75, 74, 72, 83, 82, 81, 87,
                  ],
                },
              ],
              apexMaxValue: 100,
              apexMaxAlias: "",
              apexMaxColor: "#04beaf",
              timeframe: 0,
              fiwareService: "Luftfeuchtigkeit",
              entityId: ["Luftfeuchtigkeit"],
              attribute: {
                keys: ["Luftfeuchtigkeit"],
                aliases: ["Luftfeuchtigkeit"],
              },
              values: [],
              decimals: 0,
              aggrMode: "single",
              queryData: { id: { $oid: "61f92e456eb2edbb8b0a8e32" } },
              _id: { $oid: "61f92e456eb2edbb8b0a8e4b" },
            },
          ],
          _id: { $oid: "61f92e456eb2edbb8b0a8e4a" },
        },
      ],
      _id: { $oid: "61f92b716eb2edbb8b0a88f6" },
    },
    {
      name: "Schwimmbad",
      panels: [
        {
          name: "Aktuelle Auslastung",
          width: 2,
          height: 300,
          tabs: [
            {
              name: "Tab",
              type: "chart",
              text: "",
              apexType: "donut",
              apexOptions: {
                yaxis: { forceNiceScale: true },
                dataLabels: { enabled: false },
                chart: { toolbar: { show: false }, background: "#152437" },
                stroke: { show: true, colors: ["#152437"] },
                theme: { mode: "dark", palette: "palette4" },
                colors: ["#04beaf", "#0587bb"],
                legend: { position: "top", markers: { radius: 5 } },
                xaxis: {
                  convertedCatToNumeric: false,
                  categories: [],
                  type: "category",
                  labels: { rotate: 0 },
                  tickAmount: 13,
                },
                labels: ["frei", "Besucher"],
              },
              apexSeries: [5, 95],
              apexMaxValue: 8,
              apexMaxAlias: "frei",
              apexMaxColor: "#04beaf",
              timeframe: 0,
              fiwareService: "ssd",
              entityId: ["sdsd"],
              attribute: { keys: ["attr1"], aliases: ["attr1"] },
              values: [],
              decimals: 0,
              aggrMode: "single",
              queryData: { id: { $oid: "61f1349397fe31a9d33fe4d0" } },
              _id: { $oid: "61f1349397fe31a9d33fe4dd" },
            },
          ],
          _id: { $oid: "61f1349397fe31a9d33fe4dc" },
        },
        {
          name: "Auslastung der vergangenen Woche",
          width: 4,
          height: 300,
          tabs: [
            {
              name: "Tab",
              type: "chart",
              text: "",
              apexType: "bar",
              apexOptions: {
                grid: { borderColor: "#2f3a4e" },
                yaxis: {
                  forceNiceScale: true,
                  title: { text: "Anzahl der Besucher" },
                },
                dataLabels: { enabled: false },
                fill: { opacity: 1 },
                chart: { toolbar: { show: false }, background: "#152437" },
                theme: { mode: "dark", palette: "palette4" },
                colors: ["#0587bb", "#ff9f00"],
                legend: { position: "top", markers: { radius: 5 } },
                xaxis: {
                  convertedCatToNumeric: false,
                  type: "category",
                  categories: [
                    "24.01.",
                    "25.01.",
                    "26.01.",
                    "27.01.",
                    "28.01.",
                    "29.01.",
                    "30.01.",
                  ],
                  labels: { rotate: 0 },
                  tickAmount: 13,
                },
              },
              apexSeries: [
                { name: "Besucher", data: [51, 62, 63, 74, 65, 86, 97] },
              ],
              apexMaxValue: 100,
              apexMaxAlias: "Maximale Besucher",
              apexMaxColor: "#04beaf",
              timeframe: 0,
              fiwareService: "akasjdlsd",
              entityId: ["skdjalsdj"],
              attribute: { keys: ["Besucher"], aliases: ["Besucher"] },
              values: [],
              decimals: 0,
              aggrMode: "single",
              queryData: { id: { $oid: "61f929546eb2edbb8b0a84fe" } },
              _id: { $oid: "61f929546eb2edbb8b0a850b" },
            },
          ],
          _id: { $oid: "61f929546eb2edbb8b0a850a" },
        },
        {
          name: "Wasser",
          width: 2,
          height: 300,
          tabs: [
            {
              name: "Tab",
              type: "value",
              text: "",
              apexType: "donut",
              apexOptions: {
                grid: { borderColor: "#2f3a4e" },
                yaxis: { forceNiceScale: true },
                dataLabels: { enabled: false },
                fill: { opacity: 1 },
                chart: { toolbar: { show: false }, background: "#152437" },
                theme: { mode: "dark" },
                colors: ["#0C2A5F", "#1e2738"],
              },
              apexSeries: [],
              apexMaxValue: 100,
              apexMaxAlias: "",
              apexMaxColor: "#04beaf",
              timeframe: 0,
              fiwareService: "Durchschnittl",
              entityId: ["durchscnitt"],
              attribute: {
                keys: ["durschnittTemp"],
                aliases: ["Aktuelle Wassertemperatur [°C]"],
              },
              values: [28],
              decimals: 0,
              aggrMode: "single",
              queryData: { id: { $oid: "61f937636eb2edbb8b0aa539" } },
              _id: { $oid: "61f937636eb2edbb8b0aa557" },
            },
          ],
          _id: { $oid: "61f937636eb2edbb8b0aa556" },
        },
        {
          name: "Infos",
          width: 4,
          height: 300,
          tabs: [
            {
              name: "Tab",
              type: "description",
              text: "Dieser Prototyp eines Smart City Dashboards dient zur Visualisierung von Daten aus einer FIWARE basierten Urban Data Platform. Durch die Bereitstellung der Daten, insbesondere in Form von Charts, können Bürger:innen und Interessent:innen ein Überblick über den aktuellen Sachverhalt in der Stadt gegeben werden.",
              apexType: "donut",
              apexOptions: {
                grid: { borderColor: "#2f3a4e" },
                yaxis: { forceNiceScale: true },
                dataLabels: { enabled: false },
                fill: { opacity: 1 },
                chart: { toolbar: { show: false }, background: "#152437" },
                theme: { mode: "dark" },
                colors: ["#0C2A5F"],
              },
              apexSeries: [],
              apexMaxValue: 100,
              apexMaxAlias: "",
              apexMaxColor: "#04beaf",
              timeframe: 0,
              fiwareService: "",
              entityId: [],
              attribute: { keys: [], aliases: [] },
              values: [],
              decimals: 0,
              aggrMode: "single",
              _id: { $oid: "61f93b486eb2edbb8b0aafb0" },
            },
          ],
          _id: { $oid: "61f93b486eb2edbb8b0aafaf" },
        },
      ],
      _id: { $oid: "61b8e94b2cdf79e0dea2ab59" },
    },
    {
      name: "Parken",
      panels: [
        {
          name: "Aktuelle Auslastung",
          width: 2,
          height: 300,
          tabs: [
            {
              name: "Tab",
              type: "chart",
              text: "",
              apexType: "donut",
              apexOptions: {
                grid: { borderColor: "#2f3a4e" },
                yaxis: { forceNiceScale: true },
                dataLabels: { enabled: false },
                fill: { opacity: 1 },
                chart: { toolbar: { show: false }, background: "#152437" },
                theme: { mode: "dark" },
                colors: ["#f6d702", "#ff9f00"],
                legend: { position: "top", markers: { radius: 5 } },
                labels: ["frei", "belegt"],
              },
              apexSeries: [180, 300],
              apexMaxValue: 340,
              apexMaxAlias: "frei",
              apexMaxColor: "#f6d702",
              timeframe: 0,
              fiwareService: "parhaus",
              entityId: ["parkhaus"],
              attribute: { keys: ["Belegt"], aliases: ["belegt"] },
              values: [],
              decimals: 0,
              aggrMode: "single",
              queryData: { id: { $oid: "61f93c636eb2edbb8b0ab0ee" } },
              _id: { $oid: "61f93c636eb2edbb8b0ab11a" },
            },
          ],
          _id: { $oid: "61f93c636eb2edbb8b0ab119" },
        },
        {
          name: "Auslastung des vergangenen Monats",
          width: 10,
          height: 300,
          tabs: [
            {
              name: "Tab",
              type: "chart",
              text: "",
              apexType: "bar",
              apexOptions: {
                grid: { borderColor: "#2f3a4e" },
                yaxis: {
                  forceNiceScale: true,
                  title: { text: "Belegte Parkplätze" },
                },
                dataLabels: { enabled: false },
                fill: { opacity: 1 },
                chart: { toolbar: { show: false }, background: "#152437" },
                theme: { mode: "dark", palette: "palette4" },
                colors: ["#ff9f00", "#1e2738"],
                legend: { position: "top", markers: { radius: 5 } },
                xaxis: {
                  convertedCatToNumeric: false,
                  categories: [],
                  type: "category",
                  labels: { rotate: 0 },
                  tickAmount: 13,
                },
              },
              apexSeries: [
                {
                  name: "belegte Plätze",
                  data: [
                    71, 73, 75, 83, 80, 83, 74, 75, 74, 72, 83, 82, 81, 87, 71,
                    73, 75, 83, 80, 83, 74, 75, 74, 72, 83, 82, 81, 87,
                  ],
                },
              ],
              apexMaxValue: 100,
              apexMaxAlias: "",
              apexMaxColor: "#04beaf",
              timeframe: 0,
              fiwareService: "Parkpltze",
              entityId: ["Parkplaetze"],
              attribute: { keys: ["belegt"], aliases: ["belegt"] },
              values: [],
              decimals: 0,
              aggrMode: "single",
              queryData: { id: { $oid: "61f93c636eb2edbb8b0ab0ef" } },
              _id: { $oid: "61f93c636eb2edbb8b0ab11c" },
            },
          ],
          _id: { $oid: "61f93c636eb2edbb8b0ab11b" },
        },
      ],
      _id: { $oid: "61f93c636eb2edbb8b0ab118" },
    },
  ],
  __v: 0,
});

// QueryDatas insert
db.querydatas.insertMany([
  {
    _id: "61f92e456eb2edbb8b0a8e32",
    queryConfig: {
      intervalInMinutes: 5,
      fiwareService: "Luftfeuchtigkeit",
      entityId: ["Luftfeuchtigkeit"],
      type: "chart",
      aggrMode: "single",
      apexType: "line",
      apexMaxValue: 100,
      attribute: {
        keys: ["Luftfeuchtigkeit"],
        aliases: ["Luftfeuchtigkeit"],
      },
      componentType: "",
      componentDataType: "",
      componentName: "",
      componentDescription: "",
      componentIcon: "",
      componentMinimum: 0,
      componentMaximum: 1,
      componentUnit: "",
    },
    data: [
      {
        name: "Luftfeuchtigkeit",
        data: [71, 73, 75, 83, 80, 83, 74, 75, 74, 72, 83, 82, 81, 87],
      },
    ],
    dataLabels: [
      "17.01.",
      "18.01.",
      "19.01.",
      "20.01.",
      "21.01.",
      "22.01.",
      "23.01.",
      "24.01.",
      "25.01.",
      "26.01.",
      "27.01.",
      "28.01.",
      "29.01.",
      "30.01.",
    ],
    __v: 0,
    createdAt: {
      $date: {
        $numberLong: "1643720261607",
      },
    },
    updatedAt: {
      $date: {
        $numberLong: "1656594095388",
      },
    },
    updateMsg: "Daten konnten nicht geladen werden",
  },
  {
    _id: "61f92d006eb2edbb8b0a8bda",
    queryConfig: {
      type: "chart",
      fiwareService: "temperatur",
      entityId: ["luftfeuchtigkeit"],
      attribute: {
        keys: ["Temperatur", "Temp2"],
        aliases: ["Temperatur", "Temp2"],
      },
      aggrMode: "single",
      apexType: "line",
      apexMaxValue: 100,
      intervalInMinutes: 5,
      componentType: "",
      componentDataType: "",
      componentName: "",
      componentDescription: "",
      componentIcon: "",
      componentMinimum: 0,
      componentMaximum: 1,
      componentUnit: "",
    },
    data: [
      {
        name: "minimale Temperatur",
        data: [1, 3, 4, 3, 0, 2, 3, 4, 4, 2, 2, 1, 0, -1],
      },
      {
        name: "maximale Temperatur",
        data: [3, 4, 6, 5, 2, 6, 7, 7, 7, 5, 4, 5, 3, 2],
      },
    ],
    dataLabels: [
      "17.01.",
      "18.01.",
      "19.01.",
      "20.01.",
      "21.01.",
      "22.01.",
      "23.01.",
      "24.01.",
      "25.01.",
      "26.01.",
      "27.01.",
      "28.01.",
      "29.01.",
      "30.01.",
    ],
    __v: 0,
    createdAt: {
      $date: {
        $numberLong: "1643719936755",
      },
    },
    updatedAt: {
      $date: {
        $numberLong: "1656594095404",
      },
    },
    updateMsg: "Daten konnten nicht geladen werden",
  },
  {
    _id: "61f1349397fe31a9d33fe4d0",
    queryConfig: {
      type: "chart",
      fiwareService: "ssd",
      entityId: ["sdsd"],
      attribute: {
        keys: ["attr1"],
        aliases: ["attr1"],
      },
      aggrMode: "single",
      apexType: "donut",
      apexMaxValue: 8,
      apexMaxAlias: "frei",
      intervalInMinutes: 5,
      componentType: "",
      componentDataType: "",
      componentName: "",
      componentDescription: "",
      componentIcon: "",
      componentMinimum: 0,
      componentMaximum: 1,
      componentUnit: "",
    },
    data: [5, 95],
    dataLabels: ["frei", "Besucher"],
    __v: 0,
    createdAt: {
      $date: {
        $numberLong: "1643197587841",
      },
    },
    updatedAt: {
      $date: {
        $numberLong: "1656594260458",
      },
    },
    updateMsg: "Daten konnten nicht geladen werden",
  },
  {
    _id: "61f937636eb2edbb8b0aa539",
    queryConfig: {
      type: "value",
      fiwareService: "Durchschnittl",
      entityId: ["durchscnitt"],
      attribute: {
        keys: ["durschnittTemp"],
        aliases: ["Aktuelle Wassertemperatur [°C]"],
      },
      aggrMode: "single",
      apexType: "donut",
      apexMaxValue: 100,
      intervalInMinutes: 5,
      componentType: "",
      componentDataType: "",
      componentName: "",
      componentDescription: "",
      componentIcon: "",
      componentMinimum: 0,
      componentMaximum: 1,
      componentUnit: "",
    },
    data: [28],
    dataLabels: [],
    __v: 0,
    createdAt: {
      $date: {
        $numberLong: "1643722595930",
      },
    },
    updatedAt: {
      $date: {
        $numberLong: "1656594260460",
      },
    },
    updateMsg: "Daten konnten nicht geladen werden",
  },
  {
    _id: "61f93c636eb2edbb8b0ab0ee",
    queryConfig: {
      intervalInMinutes: 5,
      fiwareService: "parhaus",
      entityId: ["parkhaus"],
      type: "chart",
      aggrMode: "single",
      apexType: "donut",
      apexMaxValue: 340,
      apexMaxAlias: "frei",
      attribute: {
        keys: ["Belegt"],
        aliases: ["belegt"],
      },
      componentType: "",
      componentDataType: "",
      componentName: "",
      componentDescription: "",
      componentIcon: "",
      componentMinimum: 0,
      componentMaximum: 1,
      componentUnit: "",
    },
    data: [180, 300],
    dataLabels: ["frei", "belegt"],
    __v: 0,
    createdAt: {
      $date: {
        $numberLong: "1643723875755",
      },
    },
    updatedAt: {
      $date: {
        $numberLong: "1656594265463",
      },
    },
    updateMsg: "Daten konnten nicht geladen werden",
  },
  {
    _id: "61f93c636eb2edbb8b0ab0ef",
    queryConfig: {
      type: "chart",
      fiwareService: "Parkpltze",
      entityId: ["Parkplaetze"],
      attribute: {
        keys: ["belegt"],
        aliases: ["belegt"],
      },
      aggrMode: "single",
      apexType: "bar",
      apexMaxValue: 100,
      intervalInMinutes: 5,
      componentType: "",
      componentDataType: "",
      componentName: "",
      componentDescription: "",
      componentIcon: "",
      componentMinimum: 0,
      componentMaximum: 1,
      componentUnit: "",
    },
    data: [
      {
        name: "belegte Plätze",
        data: [
          71, 73, 75, 83, 80, 83, 74, 75, 74, 72, 83, 82, 81, 87, 71, 73, 75,
          83, 80, 83, 74, 75, 74, 72, 83, 82, 81, 87,
        ],
      },
    ],
    dataLabels: [],
    __v: 0,
    createdAt: {
      $date: {
        $numberLong: "1643723875756",
      },
    },
    updatedAt: {
      $date: {
        $numberLong: "1656594115413",
      },
    },
    updateMsg: "Daten konnten nicht geladen werden",
  },
]);
