= Smart City Suite

== Local Development

To run the application locally, make sure all the prerequisites are installed (Rancher Desktop, Node.js (v.20.13.0), PgAdmin/DBeaver, K9S) and then install the dependencies for all packages (`npm install` in root, frontend, microservices).

Afterwards you can continue the setup with kubernetes link:./k8s/README.adoc[here].

== Single Sign On

We use https://www.keycloak.org/[Keycloak] as our Single Sign On (SSO) provider.

For local development, the SSO can be accessed at http://localhost:8080/[http://localhost:8080/].

You can find more information about the Auth link:./keycloak/README.adoc[here].

== Database

Locally, we run a https://www.postgresql.org/[PostgreSQL] database via kubernetes.

Before you can develop or test locally, you will need to setup the database and run the migrations:

* link:./database/README.adoc#local-setup[Local Setup]
* link:./database/README.adoc#migrations#migrations[Migrations]

== Microservices (backend)

The backend is composed of several https://docs.nestjs.com/[NestJS] microservices. They are all part of the same monorepo in the `microservices` directory.

The link:./microservices[monorepo] contains the following microservices:

* link:./microservices/apps/dashboard-service[dashboard-service]: Responsible for serving data to the frontend and handling configuration changes.
* link:./microservices/apps/ngsi-service[ngsi-service]: Responsible for handling requests that need to be made using the NGSI API.
* link:./microservices/apps/orchideo-connect-service[orchideo-connect-service]: Responsible for handling requests that need to be made using the orchideo connect dataplatform.
