replicaCount: 1

image:
  repository: smartcity/data-translation-service
  pullPolicy: IfNotPresent
  tag: "latest"

# Remove container ports since no HTTP endpoint is needed
container: {}

# Remove service configuration since no network service is needed
service:
  enabled: false

# Remove ingress since no external access is needed
ingress:
  enabled: false

# Helm Required Values
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

common:
  enabled: true
