= Local Deployment with Kubernetes (helm)

== Prequisites:

* Local Kubernetes cluster. +
  Install https://rancherdesktop.io/[rancher-desktop] as admin. Admin rights are important otherwise the kube config might not be populated with the rancher context. +
  Rancher comes with a Kubernetes engine installed.
* Nice-To-Have: K9S - Terminal UI very useful for managing k8s deployments. +
  You can manually restart pods, easily view their logs, port forward containers and many more useful features.

== k8s Directory Structure Breakdown

* *Chart.yaml:* In the helm directory the Chart.yaml defines the dependencies that will be installed.
E.g. postgres will pull its image from the bitnami URL and insert to the charts subdir.

* *values.yaml:* Here we define the env variables of the dependencies defined in the main Chart.yaml file.
E.g. we can configure envFrom to point to a configmap to get the env variables for the postgres db.

* *templates:* When installing the helm chart, it looks for a 'templates' directory and configures all yaml inside as env
variables. Inside we have 'configmaps' for defining not-so confidential env vars such as hosts/ports.  We also have 'secrets'
for defining confidential env vars like passwords.

* *charts:* When installing the helm chart, it looks for a 'charts' directory where additional Charts & values files may be
contained and includes these in the installation.  Here we would store the Chart and values yaml for each microservice and
the frontend.

* *charts/common:*  The 'common' folder is a helm generated folder which includes templates for k8s deployments, services,
ingresses etc.  We reference these templates in the 'templates/service' & 'templates/deployment' files of each microservice & frontend
chart.  The templates that are referenced are then populated by whatever is defined in the values.yaml of each
microservice & frontend chart.

== Local Deployment

=== TLDR
[source,bash]
----
docker build -t smartcity/migrations -f Dockerfile.migrations .
kubectl create namespace smart-city-local
cd k8s/helm
helm dependency build
helm install smart-city --namespace smart-city-local -f values.yaml -f values-local.yaml -f values-infrastructure.yaml .
kubectl port-forward smart-city-keycloak-0 8080:8080 -n smart-city-local
kubectl port-forward smart-city-postgresql-0  5432:5432 -n smart-city-local
npm run db:migrate:dev
----

=== Create the image for our automatic db migrations container

[source,bash]
----
docker build -t smartcity/migrations -f Dockerfile.migrations .
----

=== Create a Kubernetes namespace
Note: this only needs to be done once on initial local cluster setup.

[source,bash]
----
kubectl create namespace smart-city-local
----

Delete Kubernetes namespace

[source,bash]
----
kubectl delete namespace smart-city-local
----

=== Build helm dependencies
Installs the dependencies defined in the Chart.yaml files

[source,bash]
----
cd k8s/helm
helm dependency build
----

=== Update helm dependencies
Updates the dependencies defined in the Chart.yaml files

[source,bash]
----
helm dependency update
----

=== Install infrastructure only (postgres & keycloak)
Performs a fresh installation of the helm charts with passed values.yaml file(s)

[source,bash]
----
helm install smart-city --namespace smart-city-local -f values.yaml -f values-local.yaml -f values-infrastructure.yaml .
----

=== Uninstall helm chart
Performs an uninstall of the specified charts

[source,bash]
----
helm uninstall smart-city --namespace smart-city-local
----

=== Port-forwarding k8s pods
It may be necessary to port-forward kubernetes pods to your localhost for the following use-cases:

**Keycloak realm creation**
* To manually create or import a new keycloak realm we can portfoward the running keycloak pod to our localhost and access it in the browser.
* This can be done simply with the K9S UI tool by performing "SHIFT + F" on the keycloak pod **OR** with the following command:

[source,bash]
----
kubectl port-forward smart-city-keycloak-0 8080:8080 -n smart-city-local
----

* Keycloak can then be accessed at localhost:8080 and realms can be imported or created here.

**Postgres db migration**
* Another use-case of port forwarding here may be to apply database migrations to the postgres instance running in the cluster.
* We can port-forward again using K9S or the following command:

[source,bash]
----
kubectl port-forward smart-city-postgresql-0  5432:5432 -n smart-city-local
----

* We can then, as normal, run the migration command:

[source,bash]
----
 npm run db:migrate:dev
----

== EDAG Deployment with Kubernetes (helm)

=== Prequisites

=== Configure EDAG kubernetes cluster
When connected to the EDAG network, the config file to setup the EDAG K8S cluster on your local rancher desktop can be found at the url:

**https://loginapp.container.edag**

* At this URL, navigate to "Full KubeConfig" and copy the contents.
* Paste the Full KubeConfig into your **.kube/config** file, replacing what is already inside.
* This .kube folder is installed with rancher desktop and can be found at this example path: "C:\Users\lc88645\ .kube"

=== Build helm dependencies
Installs the dependencies defined in the Chart.yaml files

=== Specify the target image tag
In the file: **k8s/helm/values-edag.yaml** , we can specify the image tag which we want to deploy.
The options are:
* 'latest-dev' - which is the latest build on our dev branch.
* 'latest-feature' - which is the latest commit to a feature branch.
* 'latest-PR' - which is the latest commit to an open PR.
* 'latest-testing' - which is the latest commit to a testing branch
* 'latest-bugfix' - which is the latest commit to a bugfix branch

[source,bash]
----
cd k8s/helm
helm dependency build
----

== Deploy to dev environment

=== Install all helm charts
Performs a fresh installation of the helm charts with passed values.yaml file(s)

[source,bash]
----
helm install smart-city --namespace mit-smartcity-suite-dev -f values.yaml -f values-edag.yaml -f values-edag-dev.yaml .
----

=== Uninstall helm chart
Performs an uninstall of the specified charts

[source,bash]
----
helm uninstall smart-city --namespace mit-smartcity-suite-dev
----

=== Update helm chart
Performs an update of the specified charts if there is already an existing deployment.

[source,bash]
----
helm upgrade smart-city --namespace mit-smartcity-suite-dev -f values.yaml -f values-edag.yaml -f values-edag-dev.yaml .
----

== Deploy to test environment

=== Install all helm charts
Performs a fresh installation of the helm charts with passed values.yaml file(s)

[source,bash]
----
helm install smart-city --namespace mit-smartcity-suite-test -f values.yaml -f values-edag.yaml -f values-edag-test.yaml .
----

=== Uninstall helm chart
Performs an uninstall of the specified charts

[source,bash]
----
helm uninstall smart-city --namespace mit-smartcity-suite-test
----

=== Update helm chart
Performs an update of the specified charts if there is already an existing deployment.

[source,bash]
----
helm upgrade smart-city --namespace mit-smartcity-suite-test -f values.yaml -f values-edag.yaml -f values-edag-test.yaml .
----

== Deploy to prod environment

=== Install all helm charts
Performs a fresh installation of the helm charts with passed values.yaml file(s)

[source,bash]
----
helm install smart-city --namespace mit-smartcity-suite-prod -f values.yaml -f values-edag.yaml -f values-edag-prod.yaml .
----

=== Uninstall helm chart
Performs an uninstall of the specified charts

[source,bash]
----
helm uninstall smart-city --namespace mit-smartcity-suite-prod
----

=== Update helm chart
Performs an update of the specified charts if there is already an existing deployment.

[source,bash]
----
helm upgrade smart-city --namespace mit-smartcity-suite-prod -f values.yaml -f values-edag.yaml -f values-edag-prod.yaml .
----

== Deploy to our Hetzner Cloud kubernetes environment

Switch our k8s (rancher) context to k3s, which is the kubernetes server deployed on our hcloud.

=== Install all helm charts
Performs a fresh installation of the helm charts with passed values.yaml file(s)

[source,bash]
----
helm install smart-city --namespace hcloud -f values.yaml -f values-hcloud.yaml .
----

=== Uninstall helm chart
Performs an uninstall of the specified charts

[source,bash]
----
helm uninstall smart-city --namespace hcloud
----

=== Update helm chart
Performs an update of the specified charts if there is already an existing deployment.

[source,bash]
----
helm upgrade smart-city --namespace hcloud -f values.yaml -f values-hcloud.yaml .
----



== Migrations Pod - automatic database migrations

* During the helm installing, a migrations pod will be deployed.
* This pod uses the image defined in the Dockerfile.migrations file, where the 'npm run db:migrate:dev' command is executed, running the migrations scripts.
* This pod is a Job which is executed once on initial helm deployment.
* The migrations are ran on the postgres instance defined in the postgresql-connection-configmap.yaml, located at path k8s/helm/templates/configmaps.
* The postgres values here may be altered to point to a different postgres instance hosted elsewhere.
* NOTE: If for any reason, the migrations should be restarted while keeping up the other helm charts, we can delete the job (via k9s or kubectl) and run the helm upgrade command.
