{{ define "common.service" }}

{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-city.fullname" . }}
  labels:
    {{- include "smart-city.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smart-city.selectorLabels" . | nindent 4 }}
{{- end }}
{{end}}
