FROM quay.io/keycloak/keycloak:21.1

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KEYCLOAK_FRONTEND_URL=http://localhost:3000/auth

EXPOSE 8080

COPY ./keycloak/import /opt/keycloak/data/import/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
