apiVersion: v2
name: project-data-service
description: Smart City Dashboard Project Data Service
type: application
version: 0.1.0
appVersion: "1.0.1"

dependencies:
  - name: common
    version: 0.1.0
    condition: common.enabled
