# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qlservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qlservice
  template:
    metadata:
      labels:
        app: qlservice
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: qlservice
        image: 'gitlab.opendata-paderborn.de:5050/central/dashboard/dashboard:qlservice-1.0.0'
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
# This part will create a service for making the deployment reachable for other components
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qlservice
  name: qlservice
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: qlservice
status:
  loadBalancer: {}