apiVersion: v2
name: smart-city
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: common
    version: 0.1.0
  - name: postgresql
    condition: postgresql.enabled
    version: 13.2.9  # chart version equivalent of 16.1.0
    repository: https://charts.bitnami.com/bitnami
  - name: keycloak
    condition: keycloak.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 17.1.2
  - name: dashboard-service
    condition: dashboard-service.enabled
    version: 0.1.0
  - name: ngsi-service
    condition: ngsi-service.enabled
    version: 0.1.0
  - name: orchideo-connect-service
    condition: orchideo-connect-service.enabled
    version: 0.1.0
  - name: mail-service
    condition: mail-service.enabled
    version: 0.1.0
  - name: infopin-service
    condition: infopin-service.enabled
    version: 0.1.0
  - name: static-data-service
    condition: static-data-service.enabled
    version: 0.1.0
  - name: report-service
    condition: report-service.enabled
    version: 0.1.0
  - name: usi-platform-service
    condition: usi-platform-service.enabled
    version: 0.1.0
  - name: frontend
    condition: frontend.enabled
    version: 0.1.0
  - name: migrations
    condition: migrations.enabled
    version: 0.1.0
