## Defining the physical server to be used for our EDAG deployments
hosting:
  protocol: https
  domainName: container.edag

trustedCAFile: "certificates/trusted_ca.pem"

postgresql:
  primary:
    nodeSelector:
      location: 06-Fulda-Steinauer-Str
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

migrations:
  image:
    repository: nexus.edag.de:8206/mobit-malaysia/scs/migrations
    tag: 'latest-dev'
    pullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

keycloak:
  nodeSelector:
    location: 06-Fulda-Steinauer-Str
  proxy: edge
  production: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/issuer: ca-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

dashboard-service:
  nodeSelector:
    location: 06-Fulda-Steinauer-Str
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: ca-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
    ingressClassName: nginx
  image:
    repository: nexus.edag.de:8206/mobit-malaysia/scs/dashboard-service
    tag: 'latest-dev'
    pullPolicy: Always
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

ngsi-service:
  nodeSelector:
    location: 06-Fulda-Steinauer-Str
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: ca-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
    ingressClassName: nginx
  image:
    repository: nexus.edag.de:8206/mobit-malaysia/scs/ngsi-service
    tag: 'latest-dev'
    pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

api-service:
  nodeSelector:
    location: 06-Fulda-Steinauer-Str
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: ca-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
    ingressClassName: nginx
  image:
    repository: nexus.edag.de:8206/mobit-malaysia/scs/api-service
    tag: 'latest-dev'
    pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

mail-service:
  nodeSelector:
    location: 06-Fulda-Steinauer-Str
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: ca-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
    ingressClassName: nginx
  image:
    repository: nexus.edag.de:8206/mobit-malaysia/scs/mail-service
    tag: 'latest-dev'
    pullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

infopin-service:
  nodeSelector:
    location: 06-Fulda-Steinauer-Str
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: ca-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
    ingressClassName: nginx
  image:
    repository: nexus.edag.de:8206/mobit-malaysia/scs/infopin-service
    tag: 'latest-dev'
    pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

report-service:
  nodeSelector:
    location: 06-Fulda-Steinauer-Str
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: ca-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
    ingressClassName: nginx
  image:
    repository: nexus.edag.de:8206/mobit-malaysia/scs/report-service
    tag: 'latest-feature'
    pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

frontend:
  nodeSelector:
    location: 06-Fulda-Steinauer-Str
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: ca-issuer
      cert-manager.io/issuer-kind: ClusterIssuer
    ingressClassName: nginx
  image:
    repository: nexus.edag.de:8206/mobit-malaysia/scs/frontend
    tag: 'latest-dev'
    pullPolicy: Always
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
