hosting:
  protocol: https
  domainName: smartcity-system.de  # Update to your new domain

trustedCAFile: "certificates/hcloud_ca.pem"

migrations:
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/migrations
    tag: '0.24.5'
    pullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

keycloak:
  proxy: edge
  production: true
  ingress:
    enabled: true
    hostname: keycloak.smartcity-system.de
    tls:
      - hosts:
          - keycloak.smartcity-system.de
        secretName: keycloak-tls-secret
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

dashboard-service:
  jwks: "https://keycloak.smartcity-system.de/realms/testrealm/protocol/openid-connect/certs"
  frontendUrl: "https://smartcity-system.de"
  adminRole: "scs-admin"
  superAdminRole: "scs-super-admin"
  logRotationCron: "5 1 * * * *"
  logPath: "/logs"
  editRoles: |
    [ "editor", "tester", "scs-admin" ]
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingressClassName: nginx
    tls:
      - hosts:
          - dashboard-service.smartcity-system.de
        secretName: dashboard-service-tls-secret
    hosts:
      - host: dashboard-service.smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/dashboard-service
    tag: '0.24.5'
    pullPolicy: Always

ngsi-service:
  jwks: "https://keycloak.smartcity-system.de/realms/testrealm/protocol/openid-connect/certs"
  frontendUrl: "https://smartcity-system.de"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - ngsi-service.smartcity-system.de
        secretName: ngsi-service-tls-secret
    hosts:
      - host: ngsi-service.smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/ngsi-service
    tag: '0.24.5'
    pullPolicy: Always

orchideo-connect-service:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - orchideo-connect-service.smartcity-system.de
        secretName: orchideo-connect-service-tls-secret
    hosts:
      - host: orchideo-connect-service.smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/orchideo-connect-service
    tag: '0.24.5'
    pullPolicy: Always

mail-service:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - mail-service.smartcity-system.de
        secretName: mail-service-tls-secret
    hosts:
      - host: mail-service.smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/mail-service
    tag: '0.24.5'
    pullPolicy: Always

infopin-service:
  jwks: "https://keycloak.smartcity-system.de/realms/testrealm/protocol/openid-connect/certs"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - infopin-service.smartcity-system.de
        secretName: infopin-service-tls-secret
    hosts:
      - host: infopin-service.smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/infopin-service
    tag: '0.24.5'
    pullPolicy: Always


report-service:
  frontendUrl: "https://smartcity-system.de"
  mailServiceUrl: "https://mail-service.smartcity-system.de"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - report-service.smartcity-system.de
        secretName: report-service-tls-secret
    hosts:
      - host: report-service.smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/report-service
    tag: '0.24.5'
    pullPolicy: Always

static-data-service:
  frontendUrl: "https://smartcity-system.de"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - static-data-service.smartcity-system.de
        secretName: static-data-service-tls-secret
    hosts:
      - host: static-data-service.smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/static-data-service
    tag: '0.24.5'
    pullPolicy: Always


usi-platform-service:
  frontendUrl: "https://smartcity-system.de"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - hosts:
          - usi-platform-service.smartcity-system.de
        secretName: usi-platform-service-tls-secret
    hosts:
      - host: usi-platform-service.smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/usi-platform-service
    tag: '0.24.5'
    pullPolicy: Always


frontend:
  url: "https://smartcity-system.de"
  basepath: ""
  prefix: ""
  oidc:
    auth: "https://keycloak.smartcity-system.de/realms/testrealm"
    redirectUri: "https://smartcity-system.de"
    clientId: scs-frontend
  backendUrl: "https://dashboard-service.smartcity-system.de"
  orchideoConnectServiceUrl: "https://orchideo-connect-service.smartcity-system.de"
  usiPlatformServiceUrl: "https://usi-platform-service.smartcity-system.de"
  ngsiServiceUrl: "https://ngsi-service.smartcity-system.de"
  tlsRejectUnauthorized: "0"
  mailTo: "smart.city@edag.com"
  adminRole: "scs-admin"
  superAdminRole: "scs-super-admin"
  cbid: "087006bd-3503-4017-896e-a6bebd753657"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    className: nginx
    tls:
      - hosts:
          - smartcity-system.de
        secretName: frontend-tls-secret
    hosts:
      - host: smartcity-system.de
        paths:
          - path: /
            pathType: Prefix
  image:
    repository: ghcr.io/triveme/smartcity-dashboard/frontend
    tag: '0.24.5'
    pullPolicy: Always
