FROM node:18-alpine

RUN apk update && apk upgrade && \ 
apk add --no-cache git

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

# COPY .env .env

COPY . .

COPY package*.json ./

RUN npm install

EXPOSE 8080

CMD [ "npm", "start" ]
