import { GeoJSONFeatureCollection } from '../transformation.service';

export function getMultipleFeatureCollections(): GeoJSONFeatureCollection[] {
  return [
    {
      type: 'FeatureCollection',
      name: 'InteressanteOrte-POI_EPSG4326_JSON',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [7.2005717179, 51.2255494605],
          },
          properties: {
            HAUPTNAME: 'Ronsdorfer Sonntagsblatt',
            NAMEN: 'Wochenendzeitung für Ronsdorf/Lüttringhausen und Umgebung',
            STRASSE: 'Am Stadtbahnhof 18',
            STADT: 'Wuppertal',
            PLZ: '42369',
            TELEFON: '+49-202-246-1313',
            FAX: '+49-202-246-1314',
            EMAIL: 'info@sonntagsblatt-online.de',
            URL: 'http://www.sonntagsblatt-online.de',
            ART_INFO: 'Typ',
            INFO: 'Anzeigenzeitung (Redaktion)',
            HAUPTTHEMA: 'Medien',
            THEMEN: 'Medien',
            URL_BILD: null,
            WEB_BILD: null,
            URHEBER: null,
            KEYURL: null,
            WARTUNG: 'f',
          },
        },
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [7.080080045, 51.2383100926],
          },
          properties: {
            HAUPTNAME: 'Inline-/Skateboardanlage Vohwinkel',
            NAMEN:
              'Inline-/Skateboardanlage Herderstraße;Inline-/Skateboardanlage Homanndamm',
            STRASSE: 'Homanndamm/Herderstraße',
            STADT: 'Wuppertal',
            PLZ: '42327',
            TELEFON: null,
            FAX: null,
            EMAIL: null,
            URL: null,
            ART_INFO: 'Sportarten',
            INFO: 'Inline-Skate-Anlage und Skateboardanlage',
            HAUPTTHEMA: 'Freizeitsportangebote',
            THEMEN: 'Freizeitsportangebote',
            URL_BILD: null,
            WEB_BILD: null,
            URHEBER: null,
            KEYURL: null,
            WARTUNG: 'f',
          },
        },
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [7.1737397451, 51.2577246407],
          },
          properties: {
            HAUPTNAME: 'Evangelischer Friedhof Am Unterbarmer Friedhof',
            NAMEN: '',
            STRASSE: 'Am Unterbarmer Friedhof 16',
            STADT: 'Wuppertal',
            PLZ: '42285',
            TELEFON: null,
            FAX: null,
            EMAIL: null,
            URL: null,
            ART_INFO: 'Religionszugehörigkeit',
            INFO: 'christlich (evangelisch)',
            HAUPTTHEMA: 'Friedhöfe',
            THEMEN: 'Friedhöfe',
            URL_BILD: null,
            WEB_BILD: null,
            URHEBER: null,
            KEYURL: 'friedhof-ev-unterbarmen',
            WARTUNG: 'f',
          },
        },
      ],
    },
    {
      type: 'FeatureCollection',
      name: 'InteressanteOrte-POI_EPSG4326_JSON',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [7.2005717179, 51.2255494605],
          },
          properties: {
            HAUPTNAME: 'Ronsdorfer Sonntagsblatt',
            NAMEN: 'Wochenendzeitung für Ronsdorf/Lüttringhausen und Umgebung',
            STRASSE: 'Am Stadtbahnhof 18',
            STADT: 'Wuppertal',
            PLZ: '42369',
            TELEFON: '+49-202-246-1313',
            FAX: '+49-202-246-1314',
            EMAIL: 'info@sonntagsblatt-online.de',
            URL: 'http://www.sonntagsblatt-online.de',
            ART_INFO: 'Typ',
            INFO: 'Anzeigenzeitung (Redaktion)',
            HAUPTTHEMA: 'Medien',
            THEMEN: 'Medien',
            URL_BILD: null,
            WEB_BILD: null,
            URHEBER: null,
            KEYURL: null,
            WARTUNG: 'f',
          },
        },
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [7.080080045, 51.2383100926],
          },
          properties: {
            HAUPTNAME: 'Inline-/Skateboardanlage Vohwinkel',
            NAMEN:
              'Inline-/Skateboardanlage Herderstraße;Inline-/Skateboardanlage Homanndamm',
            STRASSE: 'Homanndamm/Herderstraße',
            STADT: 'Wuppertal',
            PLZ: '42327',
            TELEFON: null,
            FAX: null,
            EMAIL: null,
            URL: null,
            ART_INFO: 'Sportarten',
            INFO: 'Inline-Skate-Anlage und Skateboardanlage',
            HAUPTTHEMA: 'Freizeitsportangebote',
            THEMEN: 'Freizeitsportangebote',
            URL_BILD: null,
            WEB_BILD: null,
            URHEBER: null,
            KEYURL: null,
            WARTUNG: 'f',
          },
        },
        {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [7.1737397451, 51.2577246407],
          },
          properties: {
            HAUPTNAME: 'Evangelischer Friedhof Am Unterbarmer Friedhof',
            NAMEN: '',
            STRASSE: 'Am Unterbarmer Friedhof 16',
            STADT: 'Wuppertal',
            PLZ: '42285',
            TELEFON: null,
            FAX: null,
            EMAIL: null,
            URL: null,
            ART_INFO: 'Religionszugehörigkeit',
            INFO: 'christlich (evangelisch)',
            HAUPTTHEMA: 'Friedhöfe',
            THEMEN: 'Friedhöfe',
            URL_BILD: null,
            WEB_BILD: null,
            URHEBER: null,
            KEYURL: 'friedhof-ev-unterbarmen',
            WARTUNG: 'f',
          },
        },
      ],
    },
  ];
}

export function getSingleFeatureCollection(): GeoJSONFeatureCollection {
  return {
    type: 'FeatureCollection',
    name: 'InteressanteOrte-POI_EPSG4326_JSON',
    features: [
      {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [7.2005717179, 51.2255494605],
        },
        properties: {
          HAUPTNAME: 'Ronsdorfer Sonntagsblatt',
          NAMEN: 'Wochenendzeitung für Ronsdorf/Lüttringhausen und Umgebung',
          STRASSE: 'Am Stadtbahnhof 18',
          STADT: 'Wuppertal',
          PLZ: '42369',
          TELEFON: '+49-202-246-1313',
          FAX: '+49-202-246-1314',
          EMAIL: 'info@sonntagsblatt-online.de',
          URL: 'http://www.sonntagsblatt-online.de',
          ART_INFO: 'Typ',
          INFO: 'Anzeigenzeitung (Redaktion)',
          HAUPTTHEMA: 'Medien',
          THEMEN: 'Medien',
          URL_BILD: null,
          WEB_BILD: null,
          URHEBER: null,
          KEYURL: null,
          WARTUNG: 'f',
        },
      },
      {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [7.080080045, 51.2383100926],
        },
        properties: {
          HAUPTNAME: 'Inline-/Skateboardanlage Vohwinkel',
          NAMEN:
            'Inline-/Skateboardanlage Herderstraße;Inline-/Skateboardanlage Homanndamm',
          STRASSE: 'Homanndamm/Herderstraße',
          STADT: 'Wuppertal',
          PLZ: '42327',
          TELEFON: null,
          FAX: null,
          EMAIL: null,
          URL: null,
          ART_INFO: 'Sportarten',
          INFO: 'Inline-Skate-Anlage und Skateboardanlage',
          HAUPTTHEMA: 'Freizeitsportangebote',
          THEMEN: 'Freizeitsportangebote',
          URL_BILD: null,
          WEB_BILD: null,
          URHEBER: null,
          KEYURL: null,
          WARTUNG: 'f',
        },
      },
      {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [7.1737397451, 51.2577246407],
        },
        properties: {
          HAUPTNAME: 'Evangelischer Friedhof Am Unterbarmer Friedhof',
          NAMEN: '',
          STRASSE: 'Am Unterbarmer Friedhof 16',
          STADT: 'Wuppertal',
          PLZ: '42285',
          TELEFON: null,
          FAX: null,
          EMAIL: null,
          URL: null,
          ART_INFO: 'Religionszugehörigkeit',
          INFO: 'christlich (evangelisch)',
          HAUPTTHEMA: 'Friedhöfe',
          THEMEN: 'Friedhöfe',
          URL_BILD: null,
          WEB_BILD: null,
          URHEBER: null,
          KEYURL: 'friedhof-ev-unterbarmen',
          WARTUNG: 'f',
        },
      },
    ],
  };
}
