{{- if index .Values.frontend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
data:
  NEXT_PUBLIC_MAPBOX_TOKEN: {{ index .Values.frontend "mapBoxToken" | b64enc | quote }}
{{- end }}
