# Encoded config variables for keycloak instance setup
{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
data:
  admin-password: YWRtaW4=
  db-host: {{ printf "%v-postgresql" .Release.Name | b64enc }} ## encoded smartcity-postgresql
  db-password: YWRtaW4=
{{- end }}
