{{- if or (index .Values "dashboard-service" "enabled") (index .Values "orchideo-connect-service" "enabled") (index .Values "ngsi-service" "enabled") (index .Values "migrations" "enabled") }}
# Encoded env vars specific for establishing connection between microservice and postgres
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-connection-secrets
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  PGPASSWORD: cG9zdGdyZXM= # PGPASSWORD = POSTGRES_PASSWORD - PGPASSWORD is a postgres defined value which sets the password for the psql command in Dockerfile.migrations
{{- end }}
