{{- if index .Values "usi-platform-service" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: usi-platform-service-secrets
type: Opaque
data:
  USI_CLIENT_SECRET: {{ index .Values "usi-platform-service" "usiClientSecret" | b64enc | quote }}
{{- end }}
