const WORKBOOK_ATTRIBUTE_LABELS: Record<string, string> = {
  ADDRESSREGION: 'Region',
  ADRESSLOCALITY: 'Ort',
  ALERTDESCRIPTION: 'Warntext',
  ALERTSOURCE: 'Warnquelle',
  ALL_GATEWAYS: 'Gateways',
  AVAILABLESPOTNUMBER: 'freie Pl\u00e4tze',
  AVG_CO2_MONTHLY: 'CO2 Durchschnitt Monat',
  AVG_CO2_PREV_DAY: 'CO2 Durchschnitt Vortag',
  AVG_OCCUPIED_HOURS_30D: 'Parkdauer Durchschnitt',
  AVG_OCCUPIED_HOURS_ALL_30D: 'Parkdauer Durchschnitt in Stunden',
  AVG_OCCUPIED_MIN_DAILY: 'Parkdauer Durchschnitt t\u00e4glich',
  AVG_OCCUPIED_MIN_WEEKLY: 'Parkdauer Durchschnitt w\u00f6chentlich',
  AVG_OCCUPIED_PERCENT_ALL_30D: 'Parkdauer Durchschnitt in %',
  AVG_OCCUPIED_PERCENT_DAILY: 'Parkdauer Durchschnitt t\u00e4glich in Prozent',
  AVG_OCCUPIED_PERCENT_WEEKLY:
    'Parkdauer Durchschnitt w\u00f6chentlich in Prozent',
  AVG_TEMP_DEW_DIFF_MONTHLY: 'Taupunktdiff. Durchschnitt Monat',
  AVG_TEMP_DEW_DIFF_PREV_DAY: 'Taupunktdiff. Durchschnitt Vortag',
  AVG_TEMP_MONTHLY: 'Temperatur Durchschnitt Monat',
  AVG_TEMP_PREV_DAY: 'Temperatur Durchschnitt Vortag',
  BATTERY: 'Batterie',
  BATTERYSTATUS: 'Batteriestatus',
  CAREUNIT: 'Pflegestatus',
  DATA: 'Daten',
  DATEFELLED: 'F\u00e4lldatum',
  DATEISSUED: 'Ausgabedatum',
  DAYS: 'Tage',
  DETAILURL: 'Details',
  DURATIONTEXT: 'Dauer Textformat',
  EAST_WINDSPEED: 'Windgeschwindigkeit Ost',
  END_DATE: 'Ende',
  FREE_SLOTS: 'Freie Pl\u00e4tze',
  GATEWAY_ID: 'Gateway ID',
  HOTTEST_DAY: 'Hei\u00dfster Tag',
  HOUR: 'Stunde',
  INCLINATION_DEGREE: 'Neigung',
  INSTRUCTION: 'Handlungsempfehlung',
  LIGHTNING_AVERAGE_DISTANCE: 'Blitzdistanz',
  LIGHTNING_STRIKE_COUNTER: 'Blitzanzahl',
  LIGHTNING_STRIKE_DATE: 'letzter Blitzeinschlag',
  LINPERCENTVALUE: 'F\u00fcllstand',
  LOCATION: 'Ort',
  MAX_CO2_MONTHLY: 'CO2 max. Monat',
  MAX_CO2_PREV_DAY: 'CO2 max. Vortag',
  MAX_PRECIPITATION: 'max. Niederschlag',
  MAX_TEMP_DEW_DIFF_MONTHLY: 'Taupunktdiff. max. Monat',
  MAX_TEMP_DEW_DIFF_PREV_DAY: 'Taupunktdiff. max. Vortag',
  MAX_TEMP_MONTHLY: 'Temperatur max. Monat',
  MAX_TEMP_PREV_DAY: 'Temperatur max. Vortag',
  MAXCURRENTLEVEL: 'max. Wasserstand',
  MAXDATEOBSERVED: 'max. Wasserstand Datum',
  MAXLVL_DATE: 'max. Pegelstand Datum',
  MEASUREDDISTANCE: 'Abstand gemessen',
  MIN_CO2_MONTHLY: 'CO2 min. Monat',
  MIN_CO2_PREV_DAY: 'CO2 min. Vortag',
  MIN_TEMP_DEW_DIFF_MONTHLY: 'Taupunktdiff. min. Monat',
  MIN_TEMP_DEW_DIFF_PREV_DAY: 'Taupunktdiff. min. Vortag',
  MIN_TEMP_MONTHLY: 'Temperatur min. Monat',
  MIN_TEMP_PREV_DAY: 'Temperatur min. Vortag',
  MINCURRENTLEVEL: 'min. Wasserstand',
  MINDATEOBSERVED: 'min. Wasserstand Datum',
  MINLVL_DATE: 'min. Pegelstand Datum',
  NORTH_WINDSPEED: 'Windgeschwindigkeit Nord',
  NUM_DAYS: 'Anzahl Tage',
  OCCUPIED_SECONDS: 'Parkdauer Sek.',
  OCCUPIED_SLOTS: 'Belegte Pl\u00e4tze',
  PERCENTVALUE: 'Messwert Prozent',
  PICTURE: 'Bild',
  RAIN_VALUE: 'Regenmenge',
  RAINDURATION_MIN: 'Regendauer',
  RAINRATE10MIN: 'Regenmenge (10 min)',
  REFPARKINGSITE: 'Parkplatz',
  RESULT: 'Ergebnis',
  RSSI: 'Signal RSSi',
  SCALEDVALUE: 'Messwert',
  SEVERITY: 'Stufe',
  SNR: 'Signal SNR',
  SOILMOISTUREVWC_10CM: 'Bodenfeuchte 10cm',
  SOILMOISTUREVWC_20CM: 'Bodenfeuchte 20cm',
  SOILMOISTUREVWC_30CM: 'Bodenfeuchte 30cm',
  SOILMOISTUREVWC_45CM: 'Bodenfeuchte 45cm',
  SOILMOISTUREVWC_60CM: 'Bodenfeuchte 60cm',
  SOILMOISTUREVWC_90CM: 'Bodenfeuchte 90cm',
  START_DATE: 'Start',
  STREETADDRESS: 'Stra\u00dfe',
  SUBCATEGORY: 'Unterkategorie',
  TEXT: 'Text',
  TEXT_COUNTER: 'Anzahl Textformat',
  TEXT_YEARLY_MAX: 'Text j\u00e4hrlich',
  TREEHEIGHT: 'H\u00f6he',
  TREETYPEBOTANICAL: 'Baumart botanisch',
  UNKNOWN_SLOTS: 'Unbekannte Pl\u00e4tze',
  VALIDFROM: 'g\u00fcltig ab',
  VALIDTO: 'g\u00fcltig bis',
  WATERLEAK1: 'Leckage Sensor 1',
  WATERLEAK2: 'Leckage Sensor 2',
  WATERLEAKOVERALL: 'Leckagestatus',
  WATERREQUIREMET: 'Wasserbedarf',
  WEEKDAY: 'Wochentag',
  YEARPLANTED: 'Pflanzjahr',
};

const LEGACY_BACKEND_ATTRIBUTE_LABELS: Record<string, string> = {
  MONTHLYCONSUMPTIONSUMGAS: 'Monatlicher Gasverbrauch',
  MONTHLYCONSUMPTIONSUMWATER: 'Monatlicher Wasserverbrauch',
  CO2: 'CO2',
  SOILMOISTUREEC: 'Bodenfeuchtigkeit',
  SOILMOISTUREVWC: 'Bodenfeuchtigkeit',
  SOILMOISTUREVWC_TIEFE_1: 'Bodenfeuchtigkeit 10cm',
  SOILMOISTUREVWC_TIEFE_2: 'Bodenfeuchtigkeit 25cm',
  SOILMOISTUREVWC_TIEFE_3: 'Bodenfeuchtigkeit 50cm',
  SOILMOISTUREVWC_TIEFE_4: 'Bodenfeuchtigkeit 75cm',
  SOILMOISTUREVWC_TIEFE_5: 'Bodenfeuchtigkeit 90cm',
  SOILMOISTUREVWC_TIEFE_6: 'Bodenfeuchtigkeit 1m',
  SOILMOISTUREVWC_TIEFE_10CM: 'Bodenfeuchtigkeit 10cm',
  SOILMOISTUREVWC_TIEFE_20CM: 'Bodenfeuchtigkeit 20cm',
  SOILMOISTUREVWC_TIEFE_30CM: 'Bodenfeuchtigkeit 30cm',
  SOILMOISTUREVWC_TIEFE_45CM: 'Bodenfeuchtigkeit 45cm',
  SOILMOISTUREVWC_TIEFE_60CM: 'Bodenfeuchtigkeit 60cm',
  SOILMOISTUREVWC_TIEFE_90CM: 'Bodenfeuchtigkeit 90cm',
  SOILTEMPERATURE: 'Bodentemperatur',
  TOTALCONSUMPTIONSUM_GAS: 'Gesamtverbrauch Gas',
  TOTALCONSUMPTIONSUM_WATER: 'Gesamtverbrauch Wasser',
  CO2AVG: 'CO2 Durchschnitt',
  TEMPERATURE: 'Temperatur',
  CURRENTLEVEL: 'Pegelstand',
  CURRENT_LEVEL: 'Pegelstand',
  DEWPOINT: 'Taupunkt',
  RELATIVEHUMIDITY: 'Relative Luftfeuchte',
  SOILTEMPERATUR: 'Boden Temperatur',
  PRECIPITATION: 'Niederschlag',
  RAINRATEINTERVAL: 'Niederschlag',
  IRRADIATION: 'Sonneneinstrahlung',
  PRESSURE: 'Luftdruck',
  SOLARRADIATION: 'Solareinstrahlung',
  LIGHTNING_STRIKE_COUNT: 'Blitzeinschl\u00e4ge',
  LIGHTNING_STRIKE_DISTANCE: 'Blitzentfernung',
  WINDDIRECTION: 'Windrichtung',
  MAXIMUM_WINDSPEED: 'Windb\u00f6e',
  WINDSPEED: 'Windgeschwindigkeit',
  TOTAL_COVERAGE: 'Bew\u00f6lkung',
  MAXLVL: 'H\u00f6chster Pegelstand',
  MINLVL: 'Niedrigster Pegelstand',
  ATMOSPHERICPRESSURE: 'Luftdruck',
  VEHICLETYPE: 'Fahrzeugtyp',
  STREETNAME: 'Stra\u00dfenname',
  INTENSITY: 'Auslastung',
  STATUS_ISOCCUPIEDSUM: 'Belegung',
  LIGHTNING_AVERAGE_DISTANCE: 'Blitzentfernung',
  CAR: 'PKW',
  PKW: 'PKW',
  AUTO: 'PKW',
  BIKE: 'Fahrrad',
  BICYCLE: 'Fahrrad',
  BICYCLES: 'Fahrrad',
  FAHRRAD: 'Fahrrad',
  SCOOTER: 'Roller',
  MOTORRAD: 'Motorrad',
  MOTORBIKE: 'Motorrad',
  MOTORCYCLE: 'Motorrad',
  MOTORCYCLES: 'Motorrad',
  ELECTRIC_CAR: 'Elektroauto',
  ELECTRIC_BIKE: 'Elektrofahrrad',
  ELECTRIC_SCOOTER: 'Elektroroller',
  ELECTRIC_MOTORBIKE: 'Elektromotorrad',
  BUS: 'Bus',
  BUSES: 'Bus',
  LKW: 'LKW',
  TRUCK: 'LKW',
  TRUCKS: 'LKW',
  PASSANT: 'Person',
  PERSON: 'Person',
  TOTALCONSUMPTION: 'Verbrauch',
  ANZAHL_LKW: 'LKW',
  ANZAHL_MOTORRAD: 'Motorrad',
  ANZAHL_PERSON: 'Person',
  ANZAHL_PKW: 'PKW',
  ANZAHL_SONSTIGE: 'Sonstige',
  SONSTIGE: 'Sonstige',
  ATMOSPHERICPRESSUREAVG: 'Luftdruck',
  PRECIPITATIONAVG: 'Niederschlag',
  RELATIVEHUMIDITYAVG: 'Luftfeuchte',
  TEMPERATUREAVG: 'Temperatur',
  CO: 'Kohlenstoffmonoxid',
  NO: 'Stickstoffmonoxid',
  NO2: 'Stickstoffdioxid',
  O3: 'Ozon',
  PM1: 'Feinstaub PM1',
  PM10: 'Feinstaub PM10',
  PM25: 'Feinstaub PM2,5',
  RELATIV_FREI: 'Frei (%)',
  ARIQUALITYINDEX: 'Luftqualit\u00e4tsindex',
};

const BACKEND_ATTRIBUTE_LABELS: Record<string, string> = {
  ...WORKBOOK_ATTRIBUTE_LABELS,
  ...LEGACY_BACKEND_ATTRIBUTE_LABELS,
};

function normalizeAttributeLabelKey(attribute: string): string {
  return attribute.trim().toUpperCase();
}

export function getGermanLabelForAttribute(attribute: string): string {
  return (
    BACKEND_ATTRIBUTE_LABELS[normalizeAttributeLabelKey(attribute)] ?? attribute
  );
}
