# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Demo-Deployment

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Setup VPN config
        run: |
          echo "${{ secrets.OPEN_VPN_CA_CRT }}" > ca.crt
          echo "${{ secrets.OPEN_VPN_TLS_CRYPT }}" > tls.key
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v1"
        with:
          config_file: ./.github/workflows/client.ovpn
          username: ${{ secrets.OPENVPN_USER }}
          password: ${{ secrets.OPENVPN_PASS }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_DEMO_SERVER }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Install frontend
        working-directory: frontend
        run: npm install
      - name: Create frontend .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_REACT_APP_BASE_URL: "https://dashboard-smartcity.de/api"
          envkey_INLINE_RUNTIME_CHUNK: false
          envkey_IMAGE_INLINE_SIZE_LIMIT: 0
          directory: frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build
      - name: Deploy frontend with rsync
        working-directory: frontend/build
        run: rsync -avz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/share/nginx/html/demo
      - name: Install frontendService
        working-directory: backend/frontendService
        run: npm install
      - name: Create frontendService .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DB_HOST: "localhost"
          envkey_DB_PORT: "27017"
          envkey_FRONTEND_HOST: "https://dashboard-smartcity.de"
          envkey_DB_USER: ${{ secrets.DEMO_DB_USER }}
          envkey_DB_PASS: ${{ secrets.DEMO_DB_PASS }}
          envkey_DB_NAME: ${{ secrets.DEMO_DB_NAME }}
          envkey_SECRET: ${{ secrets.DEMO_SECRET }}
          directory: backend/frontendService
      - name: Deploy frontendService with rsync
        working-directory: backend/frontendService
        run: rsync -avz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/demo-server/frontendService
