name: Set Package Metadata

on:
  package:
    types:
      - docker

jobs:
  set-metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set package metadata
      run: |
        # Get the Docker image name and tag from the push event
        image_name="${{ github.event.package.name }}:${{ github.event.package.version }}"

        # Use GitHub API to set package metadata
        curl -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.package-deletes-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/orgs/triveme/packages/docker/$image_name/metadata \
          -d '{"visibility": "public", "repository": "triveme/smartcity-dashboard"}'
